// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a placeholder file. Run `make proto` to generate actual code.

package walletv1

import (
	"context"

	"google.golang.org/grpc"
)

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	Enable2FA(context.Context, *Enable2FARequest) (*Enable2FAResponse, error)
	Verify2FA(context.Context, *Verify2FARequest) (*Verify2FAResponse, error)
	GetLoginHistory(context.Context, *GetLoginHistoryRequest) (*GetLoginHistoryResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) Enable2FA(context.Context, *Enable2FARequest) (*Enable2FAResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) Verify2FA(context.Context, *Verify2FARequest) (*Verify2FAResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) GetLoginHistory(context.Context, *GetLoginHistoryRequest) (*GetLoginHistoryResponse, error) {
	return nil, nil
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "wallet/v1/wallet.proto",
}

// WalletServiceServer is the server API for WalletService service.
type WalletServiceServer interface {
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	ListWallets(context.Context, *ListWalletsRequest) (*ListWalletsResponse, error)
	UpdateWallet(context.Context, *UpdateWalletRequest) (*UpdateWalletResponse, error)
	DeleteWallet(context.Context, *DeleteWalletRequest) (*DeleteWalletResponse, error)
	GenerateAddress(context.Context, *GenerateAddressRequest) (*GenerateAddressResponse, error)
	ListAddresses(context.Context, *ListAddressesRequest) (*ListAddressesResponse, error)
	GetDepositAddress(context.Context, *GetDepositAddressRequest) (*GetDepositAddressResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	ListBalances(context.Context, *ListBalancesRequest) (*ListBalancesResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) ListWallets(context.Context, *ListWalletsRequest) (*ListWalletsResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) UpdateWallet(context.Context, *UpdateWalletRequest) (*UpdateWalletResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) DeleteWallet(context.Context, *DeleteWalletRequest) (*DeleteWalletResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) GenerateAddress(context.Context, *GenerateAddressRequest) (*GenerateAddressResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) ListAddresses(context.Context, *ListAddressesRequest) (*ListAddressesResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) GetDepositAddress(context.Context, *GetDepositAddressRequest) (*GetDepositAddressResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) ListBalances(context.Context, *ListBalancesRequest) (*ListBalancesResponse, error) {
	return nil, nil
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "wallet/v1/wallet.proto",
}

// DepositServiceServer is the server API for DepositService service.
type DepositServiceServer interface {
	GetDeposit(context.Context, *GetDepositRequest) (*GetDepositResponse, error)
	ListDeposits(context.Context, *ListDepositsRequest) (*ListDepositsResponse, error)
	AllocateDepositAddress(context.Context, *AllocateDepositAddressRequest) (*AllocateDepositAddressResponse, error)
	ListDepositAddresses(context.Context, *ListDepositAddressesRequest) (*ListDepositAddressesResponse, error)
	mustEmbedUnimplementedDepositServiceServer()
}

type UnimplementedDepositServiceServer struct{}

func (UnimplementedDepositServiceServer) GetDeposit(context.Context, *GetDepositRequest) (*GetDepositResponse, error) {
	return nil, nil
}
func (UnimplementedDepositServiceServer) ListDeposits(context.Context, *ListDepositsRequest) (*ListDepositsResponse, error) {
	return nil, nil
}
func (UnimplementedDepositServiceServer) AllocateDepositAddress(context.Context, *AllocateDepositAddressRequest) (*AllocateDepositAddressResponse, error) {
	return nil, nil
}
func (UnimplementedDepositServiceServer) ListDepositAddresses(context.Context, *ListDepositAddressesRequest) (*ListDepositAddressesResponse, error) {
	return nil, nil
}
func (UnimplementedDepositServiceServer) mustEmbedUnimplementedDepositServiceServer() {}

func RegisterDepositServiceServer(s grpc.ServiceRegistrar, srv DepositServiceServer) {
	s.RegisterService(&DepositService_ServiceDesc, srv)
}

var DepositService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.DepositService",
	HandlerType: (*DepositServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "wallet/v1/wallet.proto",
}

// WithdrawalServiceServer is the server API for WithdrawalService service.
type WithdrawalServiceServer interface {
	CreateWithdrawal(context.Context, *CreateWithdrawalRequest) (*CreateWithdrawalResponse, error)
	GetWithdrawal(context.Context, *GetWithdrawalRequest) (*GetWithdrawalResponse, error)
	ListWithdrawals(context.Context, *ListWithdrawalsRequest) (*ListWithdrawalsResponse, error)
	CancelWithdrawal(context.Context, *CancelWithdrawalRequest) (*CancelWithdrawalResponse, error)
	mustEmbedUnimplementedWithdrawalServiceServer()
}

type UnimplementedWithdrawalServiceServer struct{}

func (UnimplementedWithdrawalServiceServer) CreateWithdrawal(context.Context, *CreateWithdrawalRequest) (*CreateWithdrawalResponse, error) {
	return nil, nil
}
func (UnimplementedWithdrawalServiceServer) GetWithdrawal(context.Context, *GetWithdrawalRequest) (*GetWithdrawalResponse, error) {
	return nil, nil
}
func (UnimplementedWithdrawalServiceServer) ListWithdrawals(context.Context, *ListWithdrawalsRequest) (*ListWithdrawalsResponse, error) {
	return nil, nil
}
func (UnimplementedWithdrawalServiceServer) CancelWithdrawal(context.Context, *CancelWithdrawalRequest) (*CancelWithdrawalResponse, error) {
	return nil, nil
}
func (UnimplementedWithdrawalServiceServer) mustEmbedUnimplementedWithdrawalServiceServer() {}

func RegisterWithdrawalServiceServer(s grpc.ServiceRegistrar, srv WithdrawalServiceServer) {
	s.RegisterService(&WithdrawalService_ServiceDesc, srv)
}

var WithdrawalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.WithdrawalService",
	HandlerType: (*WithdrawalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "wallet/v1/wallet.proto",
}

// AssetServiceServer is the server API for AssetService service.
type AssetServiceServer interface {
	ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error)
	GetUserAssets(context.Context, *GetUserAssetsRequest) (*GetUserAssetsResponse, error)
	GetAssetPrice(context.Context, *GetAssetPriceRequest) (*GetAssetPriceResponse, error)
	mustEmbedUnimplementedAssetServiceServer()
}

type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error) {
	return nil, nil
}
func (UnimplementedAssetServiceServer) GetUserAssets(context.Context, *GetUserAssetsRequest) (*GetUserAssetsResponse, error) {
	return nil, nil
}
func (UnimplementedAssetServiceServer) GetAssetPrice(context.Context, *GetAssetPriceRequest) (*GetAssetPriceResponse, error) {
	return nil, nil
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "wallet/v1/wallet.proto",
}

