// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. Run `make proto` to generate actual code.

package walletv1

// Placeholder types - will be replaced by protoc generated code

type RegisterRequest struct {
	Email    string
	Password string
	Phone    string
}

type RegisterResponse struct {
	User *User
}

type LoginRequest struct {
	Email     string
	Password  string
	TwoFaCode string
}

type LoginResponse struct {
	Token     string
	ExpiresAt int64
	User      *User
}

type GetProfileRequest struct{}

type GetProfileResponse struct {
	User *User
}

type UpdateProfileRequest struct {
	Phone string
}

type UpdateProfileResponse struct {
	User *User
}

type ChangePasswordRequest struct {
	OldPassword string
	NewPassword string
}

type ChangePasswordResponse struct{}

type Enable2FARequest struct{}

type Enable2FAResponse struct {
	Secret    string
	QrCodeUrl string
}

type Verify2FARequest struct {
	Code string
}

type Verify2FAResponse struct {
	Success bool
}

type GetLoginHistoryRequest struct {
	Limit int32
}

type GetLoginHistoryResponse struct {
	Histories []*LoginHistory
}

type User struct {
	Id           uint64
	Uuid         string
	Email        string
	Phone        string
	Status       int32
	KycStatus    int32
	KycLevel     int32
	TwoFaEnabled bool
	LastLoginAt  interface{}
	LastLoginIp  string
	CreatedAt    interface{}
}

type LoginHistory struct {
	Id        uint64
	Ip        string
	UserAgent string
	Device    string
	Location  string
	Status    int32
	CreatedAt interface{}
}

// Wallet types
type CreateWalletRequest struct {
	Name string
	Type int32
}

type CreateWalletResponse struct {
	Wallet *Wallet
}

type GetWalletRequest struct {
	Id   uint64
	Uuid string
}

type GetWalletResponse struct {
	Wallet *Wallet
}

type ListWalletsRequest struct{}

type ListWalletsResponse struct {
	Wallets []*Wallet
}

type UpdateWalletRequest struct {
	Id   uint64
	Name string
}

type UpdateWalletResponse struct {
	Wallet *Wallet
}

type DeleteWalletRequest struct {
	Id uint64
}

type DeleteWalletResponse struct{}

type GenerateAddressRequest struct {
	WalletId uint64
	Chain    string
	Label    string
}

type GenerateAddressResponse struct {
	Address *Address
}

type ListAddressesRequest struct {
	WalletId uint64
}

type ListAddressesResponse struct {
	Addresses []*Address
}

type GetDepositAddressRequest struct {
	Chain string
}

type GetDepositAddressResponse struct {
	Address *Address
}

type GetBalanceRequest struct {
	Chain    string
	Currency string
}

type GetBalanceResponse struct {
	Balance *Balance
}

type ListBalancesRequest struct{}

type ListBalancesResponse struct {
	Balances []*Balance
}

type Wallet struct {
	Id        uint64
	Uuid      string
	UserId    uint64
	Name      string
	Type      int32
	Status    int32
	CreatedAt interface{}
	Addresses []*Address
}

type Address struct {
	Id             uint64
	Uuid           string
	WalletId       uint64
	Chain          string
	Address        string
	Label          string
	DerivationPath string
	Type           int32
	Status         int32
	CreatedAt      interface{}
}

type Balance struct {
	Id              uint64
	WalletId        uint64
	Chain           string
	Currency        string
	ContractAddress string
	Available       string
	Frozen          string
	Pending         string
	UpdatedAt       interface{}
}

// Deposit types
type GetDepositRequest struct {
	Id   uint64
	Uuid string
}

type GetDepositResponse struct {
	Deposit *Deposit
}

type ListDepositsRequest struct {
	Page     int32
	PageSize int32
	Chain    string
	Currency string
}

type ListDepositsResponse struct {
	Deposits []*Deposit
	Total    int64
	Page     int32
	PageSize int32
}

type AllocateDepositAddressRequest struct {
	Chain string
}

type AllocateDepositAddressResponse struct {
	Address *DepositAddress
}

type ListDepositAddressesRequest struct{}

type ListDepositAddressesResponse struct {
	Addresses []*DepositAddress
}

type Deposit struct {
	Id            uint64
	Uuid          string
	UserId        uint64
	Chain         string
	TxHash        string
	FromAddress   string
	ToAddress     string
	Currency      string
	Amount        string
	Fee           string
	Status        int32
	Confirmations int32
	BlockNumber   uint64
	CreatedAt     interface{}
	CreditedAt    interface{}
}

type DepositAddress struct {
	Id        uint64
	UserId    uint64
	Chain     string
	Address   string
	Label     string
	Status    int32
	CreatedAt interface{}
}

// Withdrawal types
type CreateWithdrawalRequest struct {
	Chain           string
	ToAddress       string
	Currency        string
	Amount          string
	ContractAddress string
	Memo            string
}

type CreateWithdrawalResponse struct {
	Withdrawal *Withdrawal
}

type GetWithdrawalRequest struct {
	Id   uint64
	Uuid string
}

type GetWithdrawalResponse struct {
	Withdrawal *Withdrawal
}

type ListWithdrawalsRequest struct {
	Page     int32
	PageSize int32
	Chain    string
	Currency string
	Status   int32
}

type ListWithdrawalsResponse struct {
	Withdrawals []*Withdrawal
	Total       int64
	Page        int32
	PageSize    int32
}

type CancelWithdrawalRequest struct {
	Id uint64
}

type CancelWithdrawalResponse struct{}

type Withdrawal struct {
	Id            uint64
	Uuid          string
	UserId        uint64
	Chain         string
	TxHash        string
	FromAddress   string
	ToAddress     string
	Currency      string
	Amount        string
	Fee           string
	Status        int32
	RiskLevel     int32
	ManualReview  bool
	Confirmations int32
	Memo          string
	ErrorMsg      string
	CreatedAt     interface{}
	CompletedAt   interface{}
}

// Asset types
type ListAssetsRequest struct {
	Chain string
}

type ListAssetsResponse struct {
	Assets []*Asset
}

type GetUserAssetsRequest struct{}

type GetUserAssetsResponse struct {
	Assets        []*UserAssetDetail
	TotalValueUsd string
}

type GetAssetPriceRequest struct {
	Symbol string
}

type GetAssetPriceResponse struct {
	Price *AssetPrice
}

type Asset struct {
	Id              uint64
	Chain           string
	Symbol          string
	Name            string
	ContractAddress string
	Decimals        int32
	Type            string
	IconUrl         string
	DepositEnabled  bool
	WithdrawEnabled bool
	Status          int32
}

type AssetPrice struct {
	Symbol     string
	PriceUsd   string
	PriceBtc   string
	Change_24H string
	Volume_24H string
	UpdatedAt  interface{}
}

type UserAssetDetail struct {
	Asset     *Asset
	Available string
	Frozen    string
	Pending   string
	ValueUsd  string
}

